# app.py (Updated to always generate AI results)
import os
import json
from flask import Flask, render_template, request, send_file
from dotenv import load_dotenv
from utils.ocr import extract_text_from_pdf, extract_text_from_image
from utils.extract import extract_tests
from utils.summarizer import generate_summary
from utils.pdf_export import generate_pdf_from_html
from werkzeug.utils import secure_filename

load_dotenv()
app = Flask(__name__)
UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route('/', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        f = request.files.get('report')
        if not f:
            return render_template('index.html', error="No file uploaded.")

        try:
            filename = secure_filename(f.filename)
            file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            f.save(file_path)

            # Extract text
            if filename.lower().endswith('.pdf'):
                text = extract_text_from_pdf(file_path)
            else:
                text = extract_text_from_image(file_path)

            # Check if we have any text at all
            if not text or len(text.strip()) < 10:
                return render_template('index.html', error="Could not extract readable text from the document. Please try a clearer image or PDF.")

            # Try to extract structured test data
            tests = extract_tests(text)
            
            # Debug output
            print(f"Extracted text length: {len(text)}")
            print(f"Found {len(tests)} structured tests")
            for i, test in enumerate(tests):
                print(f"  Test {i+1}: {test['test']} = {test['value']} {test['unit']} ({test['status']})")
            
            # ALWAYS generate AI summary regardless of structured data
            try:
                summary = generate_summary(text)
                print("AI summary generated successfully")
            except Exception as e:
                print(f"AI summary generation failed: {str(e)}")
                # Provide a fallback summary
                summary = f"""
                <h3>Document Analysis</h3>
                <ul>
                    <li>Successfully extracted text from your medical document</li>
                    <li>Document contains {len(text)} characters of content</li>
                    {'<li><b>Found ' + str(len(tests)) + ' structured test results</b></li>' if tests else '<li>No structured test tables detected</li>'}
                </ul>
                <h3>Next Steps</h3>
                <ul>
                    <li>Review the extracted content below</li>
                    <li>Consult with your healthcare provider for professional interpretation</li>
                    <li>Keep this document for your medical records</li>
                </ul>
                <p><small>Note: AI analysis temporarily unavailable. Error: {str(e)}</small></p>
                """

            # Always return results - either with or without structured data
            return render_template(
                'result.html',
                original=text,
                summary=summary,
                tests=tests,
                tests_json=json.dumps(tests),
                ai_only=(len(tests) == 0),
                has_structured_data=(len(tests) > 0)
            )

        except Exception as e:
            print(f"Error processing file: {str(e)}")
            return render_template('index.html', error=f"Error processing file: {str(e)}")

    return render_template('index.html')


@app.route('/download', methods=['POST'])
def download_pdf():
    summary_html = request.form.get('summary', '')
    tests_json = request.form.get('tests', '[]')
    
    # Create comprehensive HTML for PDF
    try:
        tests = json.loads(tests_json) if tests_json else []
    except:
        tests = []
    
    # Generate enhanced HTML for PDF export
    pdf_html = f"""
    <h1>Medical Report Analysis</h1>
    
    <h2>AI Analysis Summary</h2>
    {summary_html}
    
    {f'''
    <h2>Structured Test Results</h2>
    <table border="1" style="border-collapse: collapse; width: 100%;">
        <tr>
            <th>Test</th>
            <th>Value</th>
            <th>Reference Range</th>
            <th>Status</th>
            <th>Explanation</th>
        </tr>
        {"".join([f"<tr><td>{test.get('test', '')}</td><td>{test.get('value', '')} {test.get('unit', '')}</td><td>{test.get('ref_range', '')}</td><td>{test.get('status', '')}</td><td>{test.get('explanation', '')}</td></tr>" for test in tests])}
    </table>
    ''' if tests else ''}
    
    <p><small>Generated by Medical Report Analyzer - For informational purposes only. Consult healthcare provider for medical advice.</small></p>
    """
    
    pdf_path = generate_pdf_from_html(pdf_html)
    return send_file(pdf_path, as_attachment=True)

if __name__ == '__main__':
    app.run(debug=True)

